### ISSUE TITLE
Its not working with WooCommerce Files which i have placed in plugin root.

### ISSUE THREAD

**Issue by imadeelnazar** [cpaul007/paulc-edit-oxybuilder#2]
Hello There,

I have installed the plugin but adding WooCommerce folder in root directory not working, would you please look into it and let me know if i am doing something wrong.

Thank you

**Comment by sethlewis93** [comment]
Hi, 

My findings are the same as @imadeelnazar 's above. I have followed the directives and WP is not reading those changes. Would appreciate any feedback on this. 

Thanks, 

SL

**Comment by cpaul007** [comment]
Have you followed the video? I tested and it is working for me.

**Comment by sethlewis93** [comment]
I certainly did. I can make a screen share of how I did it exactly if that would help.

SL
